List<Map<String, String>> moviesAndSeriesList = [
  {'english': 'The Godfather', 'persian': 'پدرخوانده'},
  {'english': 'Pulp Fiction', 'persian': 'داستان عامه‌پسند'},
  {'english': 'The Shawshank Redemption', 'persian': 'رستگاری در شاوشنک'},
  {'english': 'The Dark Knight', 'persian': 'شوالیه تاریکی'},
  {'english': 'Inception', 'persian': 'تلقین'},
  {'english': 'Star Wars', 'persian': 'جنگ ستارگان'},
  {'english': 'Breaking Bad', 'persian': 'افسارگسیخته'},
  {'english': 'Friends', 'persian': 'دوستان'},
  {'english': 'Game of Thrones', 'persian': 'بازی تاج و تخت'},
  {'english': 'The Lord of the Rings', 'persian': 'ارباب حلقه‌ها'},
  {'english': 'Harry Potter', 'persian': 'هری پاتر'},
  {'english': 'Avatar', 'persian': 'آواتار'},
  {'english': 'Stranger Things', 'persian': 'چیزهای عجیب'},
  {'english': 'The Matrix', 'persian': 'ماتریکس'},
  {'english': 'The Simpsons', 'persian': 'سیمپسون‌ها'},
  {'english': 'The Avengers', 'persian': 'انتقام‌جویان'},
  {'english': 'Titanic', 'persian': 'تایتانیک'},
  {'english': 'Forrest Gump', 'persian': 'فارست گامپ'},
  {'english': 'Sherlock', 'persian': 'شرلوک'},
  {'english': 'House of Cards', 'persian': 'خانه پوشالی'},
  {'english': 'The Wolf of Wall Street', 'persian': 'گرگ وال استریت'},
  {'english': 'Fight Club', 'persian': 'باشگاه مشت‌زنی'},
  {'english': 'The Silence of the Lambs', 'persian': 'سکوت بره‌ها'},
  {'english': 'Schindler\'s List', 'persian': 'فهرست شیندلر'},
  {'english': 'The Social Network', 'persian': 'شبکه اجتماعی'},
  {'english': 'Gladiator', 'persian': 'گلادیاتور'},
  {'english': 'The Departed', 'persian': 'رفتگان'},
  {'english': 'The Big Lebowski', 'persian': 'لبوفسکی بزرگ'},
  {'english': 'Mad Men', 'persian': 'مد من'},
  {'english': 'Narcos', 'persian': 'نارکس'},
  {'english': 'Black Mirror', 'persian': 'آینه سیاه'},
  {'english': 'The Crown', 'persian': 'تاج'},
  {'english': 'Money Heist', 'persian': 'سرقت پول'},
  {'english': 'La La Land', 'persian': 'لالالند'},
  {'english': 'Joker', 'persian': 'جوکر'},
  {'english': 'Parasite', 'persian': 'انگل'},
  {'english': 'No Country for Old Men', 'persian': 'جایی برای پیرمردها نیست'},
  {'english': 'The Irishman', 'persian': 'ایرلندی'},
  {'english': 'Interstellar', 'persian': 'در میان ستارگان'},
  {'english': 'The Pianist', 'persian': 'پیانیست'},
  {'english': 'Whiplash', 'persian': 'شلاق'},
  {'english': '12 Years a Slave', 'persian': '12 سال بردگی'},
  {'english': 'The Usual Suspects', 'persian': 'مظنونین همیشگی'},
  {'english': 'Memento', 'persian': 'یادگاری'},
  {'english': 'The Truman Show', 'persian': 'نمایش ترومن'},
  {'english': 'Chernobyl', 'persian': 'چرنوبیل'},
  {'english': 'The Mandalorian', 'persian': 'مندالورین'},
  {'english': 'The Witcher', 'persian': 'ویچر'},
  {'english': 'Peaky Blinders', 'persian': 'پیکی بلایندرز'},
  {'english': 'The Office', 'persian': 'اداره'},
  {'english': 'Seinfeld', 'persian': 'ساینفلد'},
  {'english': 'The Sopranos', 'persian': 'سوپرانوز'},
  {'english': 'Dexter', 'persian': 'دکستر'},
  {'english': 'True Detective', 'persian': 'کارآگاه حقیقی'},
  {'english': 'Lost', 'persian': 'گمشده'},
  {'english': 'Prison Break', 'persian': 'فرار از زندان'},
  {'english': 'How I Met Your Mother', 'persian': 'چگونه با مادرت آشنا شدم'},
  {'english': 'The Walking Dead', 'persian': 'مردگان متحرک'},
  {'english': 'Westworld', 'persian': 'وست‌ورلد'},
];
