List<Map<String, String>> animals = [
  // Land Animals
  {'english': 'Cat', 'persian': 'گربه'},
  {'english': 'Dog', 'persian': 'سگ'},
  {'english': 'Lion', 'persian': 'شیر'},
  {'english': 'Tiger', 'persian': 'ببر'},
  {'english': 'Elephant', 'persian': 'فیل'},
  {'english': 'Horse', 'persian': 'اسب'},
  {'english': 'Cow', 'persian': 'گاو'},
  {'english': 'Sheep', 'persian': 'گوسفند'},
  {'english': 'Goat', 'persian': 'بز'},
  {'english': 'Rabbit', 'persian': 'خرگوش'},
  {'english': 'Deer', 'persian': 'گوزن'},
  {'english': 'Bear', 'persian': 'خرس'},
  {'english': 'Wolf', 'persian': 'گرگ'},
  {'english': 'Fox', 'persian': 'روباه'},
  {'english': 'Zebra', 'persian': 'گورخر'},
  {'english': 'Monkey', 'persian': 'میمون'},
  {'english': 'Kangaroo', 'persian': 'کانگورو'},
  {'english': 'Giraffe', 'persian': 'زرافه'},
  {'english': 'Snake', 'persian': 'مار'},
  {'english': 'Frog', 'persian': 'قورباغه'},
  {'english': 'Chicken', 'persian': 'مرغ'},
  {'english': 'Rooster', 'persian': 'خروس'},
  {'english': 'Duck', 'persian': 'اردک'},
  {'english': 'Donkey', 'persian': 'الاغ'},
  {'english': 'Camel', 'persian': 'شتر'},
  {'english': 'Mouse', 'persian': 'موش'},
  {'english': 'Rat', 'persian': 'موش صحرایی'},
  {'english': 'Hedgehog', 'persian': 'جوجه تیغی'},
  {'english': 'Squirrel', 'persian': 'سنجاب'},
  {'english': 'Cheetah', 'persian': 'یوزپلنگ'},
  {'english': 'Leopard', 'persian': 'پلنگ'},
  {'english': 'Hyena', 'persian': 'کفتار'},
  {'english': 'Rhinoceros', 'persian': 'کرگدن'},
  {'english': 'Buffalo', 'persian': 'بوفالو'},

  // Birds
  {'english': 'Eagle', 'persian': 'عقاب'},
  {'english': 'Owl', 'persian': 'جغد'},
  {'english': 'Pigeon', 'persian': 'کبوتر'},
  {'english': 'Peacock', 'persian': 'طاووس'},
  {'english': 'Parrot', 'persian': 'طوطی'},
  {'english': 'Crow', 'persian': 'کلاغ'},
  {'english': 'Hawk', 'persian': 'شاهین'},
  {'english': 'Sparrow', 'persian': 'گنجشک'},
  {'english': 'Penguin', 'persian': 'پنگوئن'},
  {'english': 'Flamingo', 'persian': 'فلامینگو'},
  {'english': 'Swan', 'persian': 'قو'},
  {'english': 'Ostrich', 'persian': 'شترمرغ'},

  // Insects & Small Creatures
  {'english': 'Bee', 'persian': 'زنبور'},
  {'english': 'Ant', 'persian': 'مورچه'},
  {'english': 'Butterfly', 'persian': 'پروانه'},
  {'english': 'Spider', 'persian': 'عنکبوت'},
  {'english': 'Fly', 'persian': 'مگس'},
  {'english': 'Mosquito', 'persian': 'پشه'},
  {'english': 'Scorpion', 'persian': 'عقرب'},
  {'english': 'Beetle', 'persian': 'سوسک'},

  // Sea Animals
  {'english': 'Fish', 'persian': 'ماهی'},
  {'english': 'Shark', 'persian': 'کوسه'},
  {'english': 'Whale', 'persian': 'نهنگ'},
  {'english': 'Dolphin', 'persian': 'دلفین'},
  {'english': 'Octopus', 'persian': 'هشت پا'},
  {'english': 'Jellyfish', 'persian': 'عروس دریایی'},
  {'english': 'Lobster', 'persian': 'خرچنگ دریایی'},
  {'english': 'Crab', 'persian': 'خرچنگ'},
  {'english': 'Seal', 'persian': 'فک دریایی'},
  {'english': 'Sea Turtle', 'persian': 'لاک‌پشت دریایی'},
  {'english': 'Starfish', 'persian': 'ستاره دریایی'},
  {'english': 'Eel', 'persian': 'مارماهی'},
  {'english': 'Swordfish', 'persian': 'ماهی شمشیری'},
  {'english': 'Manta Ray', 'persian': 'شِـه‌پَـره دریایی'},
  {'english': 'Sea Horse', 'persian': 'اسب دریایی'},
  {'english': 'Coral', 'persian': 'مرجان'},
  {'english': 'Clam', 'persian': 'صدف'},
  {'english': 'Squid', 'persian': 'ماهی مرکب'},
  {'english': 'Barnacle', 'persian': 'مرجان دریایی'},
];
