List<Map<String, String>> countriesList = [
  {'english': 'Afghanistan', 'persian': 'افغانستان'},
  {'english': 'Albania', 'persian': 'آلبانی'},
  {'english': 'Algeria', 'persian': 'الجزایر'},
  {'english': 'Argentina', 'persian': 'آرژانتین'},
  {'english': 'Armenia', 'persian': 'ارمنستان'},
  {'english': 'Australia', 'persian': 'استرالیا'},
  {'english': 'Austria', 'persian': 'اتریش'},
  {'english': 'Azerbaijan', 'persian': 'آذربایجان'},
  {'english': 'Bahrain', 'persian': 'بحرین'},
  {'english': 'Bangladesh', 'persian': 'بنگلادش'},
  {'english': 'Belgium', 'persian': 'بلژیک'},
  {'english': 'Bolivia', 'persian': 'بولیوی'},
  {'english': 'Brazil', 'persian': 'برزیل'},
  {'english': 'Bulgaria', 'persian': 'بلغارستان'},
  {'english': 'Canada', 'persian': 'کانادا'},
  {'english': 'Chile', 'persian': 'شیلی'},
  {'english': 'China', 'persian': 'چین'},
  {'english': 'Colombia', 'persian': 'کلمبیا'},
  {'english': 'Croatia', 'persian': 'کرواسی'},
  {'english': 'Cuba', 'persian': 'کوبا'},
  {'english': 'Cyprus', 'persian': 'قبرس'},
  {'english': 'Czech Republic', 'persian': 'جمهوری چک'},
  {'english': 'Denmark', 'persian': 'دانمارک'},
  {'english': 'Egypt', 'persian': 'مصر'},
  {'english': 'Estonia', 'persian': 'استونی'},
  {'english': 'Finland', 'persian': 'فنلاند'},
  {'english': 'France', 'persian': 'فرانسه'},
  {'english': 'Germany', 'persian': 'آلمان'},
  {'english': 'Greece', 'persian': 'یونان'},
  {'english': 'Hungary', 'persian': 'مجارستان'},
  {'english': 'India', 'persian': 'هند'},
  {'english': 'Indonesia', 'persian': 'اندونزی'},
  {'english': 'Iran', 'persian': 'ایران'},
  {'english': 'Iraq', 'persian': 'عراق'},
  {'english': 'Ireland', 'persian': 'ایرلند'},
  {'english': 'Israel', 'persian': 'اسرائیل'},
  {'english': 'Italy', 'persian': 'ایتالیا'},
  {'english': 'Japan', 'persian': 'ژاپن'},
  {'english': 'Jordan', 'persian': 'اردن'},
  {'english': 'Kazakhstan', 'persian': 'قزاقستان'},
  {'english': 'Kenya', 'persian': 'کنیا'},
  {'english': 'Kuwait', 'persian': 'کویت'},
  {'english': 'Kyrgyzstan', 'persian': 'قرقیزستان'},
  {'english': 'Lebanon', 'persian': 'لبنان'},
  {'english': 'Libya', 'persian': 'لیبی'},
  {'english': 'Lithuania', 'persian': 'لیتوانی'},
  {'english': 'Malaysia', 'persian': 'مالزی'},
  {'english': 'Malta', 'persian': 'مالتا'},
  {'english': 'Mexico', 'persian': 'مکزیک'},
  {'english': 'Morocco', 'persian': 'مراکش'},
  {'english': 'Nepal', 'persian': 'نپال'},
  {'english': 'Netherlands', 'persian': 'هلند'},
  {'english': 'New Zealand', 'persian': 'نیوزیلند'},
  {'english': 'Nigeria', 'persian': 'نیجریه'},
  {'english': 'Norway', 'persian': 'نروژ'},
  {'english': 'Oman', 'persian': 'عمان'},
  {'english': 'Pakistan', 'persian': 'پاکستان'},
  {'english': 'Palestine', 'persian': 'فلسطین'},
  {'english': 'Panama', 'persian': 'پاناما'},
  {'english': 'Peru', 'persian': 'پرو'},
  {'english': 'Philippines', 'persian': 'فیلیپین'},
  {'english': 'Poland', 'persian': 'لهستان'},
  {'english': 'Portugal', 'persian': 'پرتغال'},
  {'english': 'Qatar', 'persian': 'قطر'},
  {'english': 'Romania', 'persian': 'رومانی'},
  {'english': 'Russia', 'persian': 'روسیه'},
  {'english': 'Saudi Arabia', 'persian': 'عربستان سعودی'},
  {'english': 'Singapore', 'persian': 'سنگاپور'},
  {'english': 'South Africa', 'persian': 'آفریقای جنوبی'},
  {'english': 'South Korea', 'persian': 'کره جنوبی'},
  {'english': 'Spain', 'persian': 'اسپانیا'},
  {'english': 'Sri Lanka', 'persian': 'سریلانکا'},
  {'english': 'Sudan', 'persian': 'سودان'},
  {'english': 'Sweden', 'persian': 'سوئد'},
  {'english': 'Switzerland', 'persian': 'سوئیس'},
  {'english': 'Syria', 'persian': 'سوریه'},
  {'english': 'Tajikistan', 'persian': 'تاجیکستان'},
  {'english': 'Thailand', 'persian': 'تایلند'},
  {'english': 'Tunisia', 'persian': 'تونس'},
  {'english': 'Turkey', 'persian': 'ترکیه'},
  {'english': 'Turkmenistan', 'persian': 'ترکمنستان'},
  {'english': 'Ukraine', 'persian': 'اوکراین'},
  {'english': 'United Arab Emirates', 'persian': 'امارات متحده عربی'},
  {'english': 'United Kingdom', 'persian': 'بریتانیا'},
  {'english': 'United States', 'persian': 'ایالات متحده'},
  {'english': 'Uzbekistan', 'persian': 'ازبکستان'},
  {'english': 'Venezuela', 'persian': 'ونزوئلا'},
  {'english': 'Vietnam', 'persian': 'ویتنام'},
  {'english': 'Yemen', 'persian': 'یمن'},
  {'english': 'Zambia', 'persian': 'زامبیا'},
  {'english': 'Zimbabwe', 'persian': 'زیمبابوه'}
];
