List<Map<String, String>> persianPlaces = [
  // Urban & Public Places
  {'english': 'Cafe', 'persian': 'کافه'},
  {'english': 'Restaurant', 'persian': 'رستوران'},
  {'english': 'Park', 'persian': 'پارک'},
  {'english': 'School', 'persian': 'مدرسه'},
  {'english': 'Library', 'persian': 'کتابخانه'},
  {'english': 'Mosque', 'persian': 'مسجد'},
  {'english': 'Church', 'persian': 'کلیسا'},
  {'english': 'Temple', 'persian': 'معبد'},
  {'english': 'Hospital', 'persian': 'بیمارستان'},
  {'english': 'Mall', 'persian': 'مرکز خرید'},
  {'english': 'Market', 'persian': 'بازار'},
  {'english': 'Supermarket', 'persian': 'سوپرمارکت'},
  {'english': 'Theater', 'persian': 'سینما'},
  {'english': 'Museum', 'persian': 'موزه'},
  {'english': 'Stadium', 'persian': 'استادیوم'},
  {'english': 'Airport', 'persian': 'فرودگاه'},
  {'english': 'Train Station', 'persian': 'ایستگاه قطار'},
  {'english': 'Bus Station', 'persian': 'ایستگاه اتوبوس'},
  {'english': 'Hotel', 'persian': 'هتل'},
  {'english': 'Gym', 'persian': 'باشگاه ورزشی'},
  {'english': 'Bank', 'persian': 'بانک'},
  {'english': 'Police Station', 'persian': 'کلانتری'},
  {'english': 'Post Office', 'persian': 'اداره پست'},
  {'english': 'Zoo', 'persian': 'باغ وحش'},
  {'english': 'Pharmacy', 'persian': 'داروخانه'},

  // Natural Places
  {'english': 'Forest', 'persian': 'جنگل'},
  {'english': 'Jungle', 'persian': 'جنگل استوایی'},
  {'english': 'Desert', 'persian': 'بیابان'},
  {'english': 'Mountain', 'persian': 'کوه'},
  {'english': 'Valley', 'persian': 'دره'},
  {'english': 'River', 'persian': 'رودخانه'},
  {'english': 'Lake', 'persian': 'دریاچه'},
  {'english': 'Sea', 'persian': 'دریا'},
  {'english': 'Ocean', 'persian': 'اقیانوس'},
  {'english': 'Beach', 'persian': 'ساحل'},
  {'english': 'Waterfall', 'persian': 'آبشار'},
  {'english': 'Cave', 'persian': 'غار'},
  {'english': 'Cliff', 'persian': 'صخره'},
  {'english': 'Island', 'persian': 'جزیره'},
  {'english': 'Canyon', 'persian': 'دره عمیق'},
  {'english': 'Swamp', 'persian': 'باتلاق'},
  {'english': 'Volcano', 'persian': 'آتشفشان'},

  // Residential & Private Places
  {'english': 'House', 'persian': 'خانه'},
  {'english': 'Apartment', 'persian': 'آپارتمان'},
  {'english': 'Office', 'persian': 'اداره'},
  {'english': 'Factory', 'persian': 'کارخانه'},
  {'english': 'Farm', 'persian': 'مزرعه'},
  {'english': 'Garden', 'persian': 'باغ'},
  {'english': 'Garage', 'persian': 'گاراژ'},
  {'english': 'Warehouse', 'persian': 'انبار'},
  {'english': 'Courtyard', 'persian': 'حیاط'},
  {'english': 'Living Room', 'persian': 'اتاق نشیمن'},
  {'english': 'Kitchen', 'persian': 'آشپزخانه'},
  {'english': 'Bedroom', 'persian': 'اتاق خواب'},

  // Travel & Leisure
  {'english': 'Amusement Park', 'persian': 'شهربازی'},
  {'english': 'Zoo', 'persian': 'باغ وحش'},
  {'english': 'Resort', 'persian': 'استراحتگاه'},
  {'english': 'Camping Site', 'persian': 'محل اردو زدن'},
  {'english': 'Harbor', 'persian': 'بندرگاه'},
  {'english': 'Bridge', 'persian': 'پل'},
  {'english': 'Highway', 'persian': 'بزرگراه'},
  {'english': 'Tunnel', 'persian': 'تونل'},

  // Historical & Cultural Sites
  {'english': 'Castle', 'persian': 'قلعه'},
  {'english': 'Palace', 'persian': 'کاخ'},
  {'english': 'Monument', 'persian': 'بنای یادبود'},
  {'english': 'Fort', 'persian': 'دژ'},
  {'english': 'Pyramid', 'persian': 'هرم'},
  {'english': 'Temple', 'persian': 'معبد'},
  {'english': 'Ruins', 'persian': 'ویرانه‌ها'}
];
